# Generated by Django 5.1.3 on 2024-11-06 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_rename_comment_comment_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="created_by",
        ),
    ]
