# Generated by Django 5.1.3 on 2024-11-06 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_comment_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="created_by",
        ),
    ]
